name = "Convex"
uuid = "f65535da-76fb-5f13-bab9-19810c17039a"
version = "0.12.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
MathProgBase = "^0.7"
OrderedCollections = "^1.0"
julia = "^1.0"

[extras]
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
GLPKMathProgInterface = "3c7084bd-78ad-589a-b5bb-dbd673274bea"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ECOS", "GLPKMathProgInterface", "LinearAlgebra", "Random", "SCS", "Statistics", "Test"]
