[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
